# Generated by Django 4.2.4 on 2023-08-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmpi', '0002_rename_question_malequestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='FemaleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Текст вопроса')),
            ],
        ),
    ]
