# Generated by Django 4.2.4 on 2023-08-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmpi', '0003_femalequestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AverageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale', models.CharField(max_length=1, verbose_name='Шкала')),
                ('m_male', models.FloatField(verbose_name='Мужчины M')),
                ('sigma_male', models.FloatField(verbose_name='Мужчины  δ')),
                ('m_female', models.FloatField(verbose_name='Женщины M')),
                ('sigma_female', models.FloatField(verbose_name='Женщины  δ')),
            ],
        ),
    ]
