# Generated by Django 4.2.4 on 2023-08-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmpi', '0004_averagedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='averagedata',
            name='no',
            field=models.CharField(default='', max_length=500, verbose_name='Ответы "Нет"'),
        ),
        migrations.AddField(
            model_name='averagedata',
            name='yes',
            field=models.CharField(default='', max_length=500, verbose_name='Ответы "да"'),
        ),
    ]
