# Generated by Django 4.2.4 on 2023-08-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmpi', '0005_averagedata_no_averagedata_yes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averagedata',
            name='no',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ответы "Нет"'),
        ),
        migrations.AlterField(
            model_name='averagedata',
            name='yes',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ответы "да"'),
        ),
    ]
