# Generated by Django 4.2.4 on 2023-08-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmpi', '0006_alter_averagedata_no_alter_averagedata_yes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averagedata',
            name='scale',
            field=models.CharField(max_length=5, verbose_name='Шкала'),
        ),
    ]
