# Generated by Django 4.2.4 on 2023-08-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmpi', '0007_alter_averagedata_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='averagedata',
            name='description',
            field=models.CharField(blank=True, max_length=250, verbose_name='Описание'),
        ),
    ]
