# Generated by Django 4.2.4 on 2023-08-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmpi', '0008_averagedata_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='averagedata',
            name='description',
        ),
    ]
