# Generated by Django 4.2.4 on 2023-09-01 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmpi', '0011_rename_results_resultsdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultsData',
        ),
    ]
