# Generated by Django 4.2.4 on 2023-09-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmpi', '0012_delete_resultsdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultsData',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('results', models.JSONField()),
            ],
        ),
    ]
